# Generated by Django 5.2.10 on 2026-02-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slips', '0003_slip_time_alter_tag_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='slip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slips/'),
        ),
    ]
